### ISSUE TITLE
Button "next" unreachable when restoring from seed

### ISSUE THREAD

**Issue by fullmetalScience** [MrCyjaneK/unnamed_monero_wallet#59]
The element is visible until a seed is entered, then an input field for restore height gets added. The added field apparently moves the "next"-button down below, outside the screen.

No touch-scrolling is possible (and there's no tab-key on my virtual keyboard).

armv7a Android 1.0.0 RC51 22

Very promising app!

**Comment by MrCyjaneK** [comment]
I'll drop you a build in couple hours :) the issue is now fixed
